package software.dzjz.retrieval.mapper;

import org.apache.ibatis.annotations.Param;
import software.dzjz.retrieval.model.DzjzwjModel;

import java.util.Date;
import java.util.List;

public interface DzjzwjModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZJZ_WD_WJ
     *
     * @mbg.generated Thu Dec 12 11:28:23 CST 2019
     */
    int deleteByPrimaryKey(String wjid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZJZ_WD_WJ
     *
     * @mbg.generated Thu Dec 12 11:28:23 CST 2019
     */
    int insert(DzjzwjModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZJZ_WD_WJ
     *
     * @mbg.generated Thu Dec 12 11:28:23 CST 2019
     */
    int insertSelective(DzjzwjModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZJZ_WD_WJ
     *
     * @mbg.generated Thu Dec 12 11:28:23 CST 2019
     */
    DzjzwjModel selectByPrimaryKey(String wjid);

    List<DzjzwjModel> selectByAh(String ah);

//    List<DzjzwjModel> selectBy(@Param("ah") String ah, @Param("ajmc") String ajmc, @Param("ajxz") String ajxz,
//                               @Param("wjlx") String wjlx, @Param("larq") Date larq, @Param("jarq") Date jarq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZJZ_WD_WJ
     *
     * @mbg.generated Thu Dec 12 11:28:23 CST 2019
     */
    int updateByPrimaryKeySelective(DzjzwjModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZJZ_WD_WJ
     *
     * @mbg.generated Thu Dec 12 11:28:23 CST 2019
     */
    int updateByPrimaryKey(DzjzwjModel record);
}