package software.dzjz.retrieval.mapper;

import software.dzjz.retrieval.model.SpryModel;
import software.dzjz.retrieval.model.SpryModelKey;

import java.util.List;

public interface SpryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SPRY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    int deleteByPrimaryKey(SpryModelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SPRY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    int insert(SpryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SPRY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    int insertSelective(SpryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SPRY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    SpryModel selectByPrimaryKey(SpryModelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SPRY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    int updateByPrimaryKeySelective(SpryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SPRY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    int updateByPrimaryKey(SpryModel record);

    List<SpryModel> getSprysByAjxh(Integer ajxh);
}