package software.dzjz.retrieval.mapper;

import org.apache.ibatis.annotations.Param;
import software.dzjz.retrieval.model.XtglYhbModel;

public interface XtglYhbModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XTGL_YHB
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    int insert(XtglYhbModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XTGL_YHB
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    int insertSelective(XtglYhbModel record);

    XtglYhbModel selectByYhdmAndYhkl(@Param("yhdm") String yhdm, @Param("yhkl") String yhkl);
}