package software.dzjz.retrieval.model;

import java.util.Date;

public class DzjzwjModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.WJID
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String wjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.WJSSML
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String wjssml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.AJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.AH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String ah;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.WJMC
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String wjmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.WJLX
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String wjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.WJSX
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Integer wjsx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.WJZT
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Integer wjzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.WJLJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String wjlj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.SFGD
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Integer sfgd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.SFKFY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String sfkfy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.CJR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String cjr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.CJSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.SHR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String shr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.SHSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Date shsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.SHYJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String shyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.SCR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String scr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.SCSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Date scsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.SCYY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String scyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.LADJH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String ladjh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_WJ.DJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String djxh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.WJID
     *
     * @return the value of DZJZ_WD_WJ.WJID
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getWjid() {
        return wjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.WJID
     *
     * @param wjid the value for DZJZ_WD_WJ.WJID
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setWjid(String wjid) {
        this.wjid = wjid == null ? null : wjid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.WJSSML
     *
     * @return the value of DZJZ_WD_WJ.WJSSML
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getWjssml() {
        return wjssml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.WJSSML
     *
     * @param wjssml the value for DZJZ_WD_WJ.WJSSML
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setWjssml(String wjssml) {
        this.wjssml = wjssml == null ? null : wjssml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.AJXH
     *
     * @return the value of DZJZ_WD_WJ.AJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.AJXH
     *
     * @param ajxh the value for DZJZ_WD_WJ.AJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.AH
     *
     * @return the value of DZJZ_WD_WJ.AH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getAh() {
        return ah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.AH
     *
     * @param ah the value for DZJZ_WD_WJ.AH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setAh(String ah) {
        this.ah = ah == null ? null : ah.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.WJMC
     *
     * @return the value of DZJZ_WD_WJ.WJMC
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getWjmc() {
        return wjmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.WJMC
     *
     * @param wjmc the value for DZJZ_WD_WJ.WJMC
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setWjmc(String wjmc) {
        this.wjmc = wjmc == null ? null : wjmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.WJLX
     *
     * @return the value of DZJZ_WD_WJ.WJLX
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getWjlx() {
        return wjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.WJLX
     *
     * @param wjlx the value for DZJZ_WD_WJ.WJLX
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setWjlx(String wjlx) {
        this.wjlx = wjlx == null ? null : wjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.WJSX
     *
     * @return the value of DZJZ_WD_WJ.WJSX
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Integer getWjsx() {
        return wjsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.WJSX
     *
     * @param wjsx the value for DZJZ_WD_WJ.WJSX
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setWjsx(Integer wjsx) {
        this.wjsx = wjsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.WJZT
     *
     * @return the value of DZJZ_WD_WJ.WJZT
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Integer getWjzt() {
        return wjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.WJZT
     *
     * @param wjzt the value for DZJZ_WD_WJ.WJZT
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setWjzt(Integer wjzt) {
        this.wjzt = wjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.WJLJ
     *
     * @return the value of DZJZ_WD_WJ.WJLJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getWjlj() {
        return wjlj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.WJLJ
     *
     * @param wjlj the value for DZJZ_WD_WJ.WJLJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setWjlj(String wjlj) {
        this.wjlj = wjlj == null ? null : wjlj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.SFGD
     *
     * @return the value of DZJZ_WD_WJ.SFGD
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Integer getSfgd() {
        return sfgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.SFGD
     *
     * @param sfgd the value for DZJZ_WD_WJ.SFGD
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setSfgd(Integer sfgd) {
        this.sfgd = sfgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.SFKFY
     *
     * @return the value of DZJZ_WD_WJ.SFKFY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getSfkfy() {
        return sfkfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.SFKFY
     *
     * @param sfkfy the value for DZJZ_WD_WJ.SFKFY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setSfkfy(String sfkfy) {
        this.sfkfy = sfkfy == null ? null : sfkfy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.CJR
     *
     * @return the value of DZJZ_WD_WJ.CJR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.CJR
     *
     * @param cjr the value for DZJZ_WD_WJ.CJR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setCjr(String cjr) {
        this.cjr = cjr == null ? null : cjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.CJSJ
     *
     * @return the value of DZJZ_WD_WJ.CJSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.CJSJ
     *
     * @param cjsj the value for DZJZ_WD_WJ.CJSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.SHR
     *
     * @return the value of DZJZ_WD_WJ.SHR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getShr() {
        return shr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.SHR
     *
     * @param shr the value for DZJZ_WD_WJ.SHR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setShr(String shr) {
        this.shr = shr == null ? null : shr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.SHSJ
     *
     * @return the value of DZJZ_WD_WJ.SHSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Date getShsj() {
        return shsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.SHSJ
     *
     * @param shsj the value for DZJZ_WD_WJ.SHSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setShsj(Date shsj) {
        this.shsj = shsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.SHYJ
     *
     * @return the value of DZJZ_WD_WJ.SHYJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getShyj() {
        return shyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.SHYJ
     *
     * @param shyj the value for DZJZ_WD_WJ.SHYJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setShyj(String shyj) {
        this.shyj = shyj == null ? null : shyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.SCR
     *
     * @return the value of DZJZ_WD_WJ.SCR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getScr() {
        return scr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.SCR
     *
     * @param scr the value for DZJZ_WD_WJ.SCR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setScr(String scr) {
        this.scr = scr == null ? null : scr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.SCSJ
     *
     * @return the value of DZJZ_WD_WJ.SCSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Date getScsj() {
        return scsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.SCSJ
     *
     * @param scsj the value for DZJZ_WD_WJ.SCSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setScsj(Date scsj) {
        this.scsj = scsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.SCYY
     *
     * @return the value of DZJZ_WD_WJ.SCYY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getScyy() {
        return scyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.SCYY
     *
     * @param scyy the value for DZJZ_WD_WJ.SCYY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setScyy(String scyy) {
        this.scyy = scyy == null ? null : scyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.LADJH
     *
     * @return the value of DZJZ_WD_WJ.LADJH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getLadjh() {
        return ladjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.LADJH
     *
     * @param ladjh the value for DZJZ_WD_WJ.LADJH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setLadjh(String ladjh) {
        this.ladjh = ladjh == null ? null : ladjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_WJ.DJXH
     *
     * @return the value of DZJZ_WD_WJ.DJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_WJ.DJXH
     *
     * @param djxh the value for DZJZ_WD_WJ.DJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setDjxh(String djxh) {
        this.djxh = djxh == null ? null : djxh.trim();
    }
}