package software.dzjz.retrieval.model;

import java.util.Date;

public class DzjzmlModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.MLID
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String mlid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.AJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.AH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String ah;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.MLMC
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String mlmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.MLSX
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Integer mlsx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.FMLID
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String fmlid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.SFCZWJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Integer sfczwj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.CJR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String cjr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.CJSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.JZSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Date jzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.LADJH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String ladjh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZJZ_WD_ML.DJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String djxh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.MLID
     *
     * @return the value of DZJZ_WD_ML.MLID
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getMlid() {
        return mlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.MLID
     *
     * @param mlid the value for DZJZ_WD_ML.MLID
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setMlid(String mlid) {
        this.mlid = mlid == null ? null : mlid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.AJXH
     *
     * @return the value of DZJZ_WD_ML.AJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.AJXH
     *
     * @param ajxh the value for DZJZ_WD_ML.AJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.AH
     *
     * @return the value of DZJZ_WD_ML.AH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getAh() {
        return ah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.AH
     *
     * @param ah the value for DZJZ_WD_ML.AH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setAh(String ah) {
        this.ah = ah == null ? null : ah.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.MLMC
     *
     * @return the value of DZJZ_WD_ML.MLMC
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getMlmc() {
        return mlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.MLMC
     *
     * @param mlmc the value for DZJZ_WD_ML.MLMC
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setMlmc(String mlmc) {
        this.mlmc = mlmc == null ? null : mlmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.MLSX
     *
     * @return the value of DZJZ_WD_ML.MLSX
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Integer getMlsx() {
        return mlsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.MLSX
     *
     * @param mlsx the value for DZJZ_WD_ML.MLSX
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setMlsx(Integer mlsx) {
        this.mlsx = mlsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.FMLID
     *
     * @return the value of DZJZ_WD_ML.FMLID
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getFmlid() {
        return fmlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.FMLID
     *
     * @param fmlid the value for DZJZ_WD_ML.FMLID
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setFmlid(String fmlid) {
        this.fmlid = fmlid == null ? null : fmlid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.SFCZWJ
     *
     * @return the value of DZJZ_WD_ML.SFCZWJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Integer getSfczwj() {
        return sfczwj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.SFCZWJ
     *
     * @param sfczwj the value for DZJZ_WD_ML.SFCZWJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setSfczwj(Integer sfczwj) {
        this.sfczwj = sfczwj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.CJR
     *
     * @return the value of DZJZ_WD_ML.CJR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getCjr() {
        return cjr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.CJR
     *
     * @param cjr the value for DZJZ_WD_ML.CJR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setCjr(String cjr) {
        this.cjr = cjr == null ? null : cjr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.CJSJ
     *
     * @return the value of DZJZ_WD_ML.CJSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.CJSJ
     *
     * @param cjsj the value for DZJZ_WD_ML.CJSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.JZSJ
     *
     * @return the value of DZJZ_WD_ML.JZSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Date getJzsj() {
        return jzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.JZSJ
     *
     * @param jzsj the value for DZJZ_WD_ML.JZSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setJzsj(Date jzsj) {
        this.jzsj = jzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.LADJH
     *
     * @return the value of DZJZ_WD_ML.LADJH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getLadjh() {
        return ladjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.LADJH
     *
     * @param ladjh the value for DZJZ_WD_ML.LADJH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setLadjh(String ladjh) {
        this.ladjh = ladjh == null ? null : ladjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZJZ_WD_ML.DJXH
     *
     * @return the value of DZJZ_WD_ML.DJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZJZ_WD_ML.DJXH
     *
     * @param djxh the value for DZJZ_WD_ML.DJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setDjxh(String djxh) {
        this.djxh = djxh == null ? null : djxh.trim();
    }
}