package software.dzjz.retrieval.model;

import java.util.Date;

public class SpryModel extends SpryModelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.FG
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String fg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.SFCBR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String sfcbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.SFSPZ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String sfspz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.SFDLSPY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String sfdlspy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.SFRMPSY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String sfrmpsy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.XM
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.GH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String gh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.BGYY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String bgyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.BGSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Date bgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.BGFS
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private String bgfs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.FG
     *
     * @return the value of PUB_SPRY.FG
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getFg() {
        return fg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.FG
     *
     * @param fg the value for PUB_SPRY.FG
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setFg(String fg) {
        this.fg = fg == null ? null : fg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.SFCBR
     *
     * @return the value of PUB_SPRY.SFCBR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getSfcbr() {
        return sfcbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.SFCBR
     *
     * @param sfcbr the value for PUB_SPRY.SFCBR
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setSfcbr(String sfcbr) {
        this.sfcbr = sfcbr == null ? null : sfcbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.SFSPZ
     *
     * @return the value of PUB_SPRY.SFSPZ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getSfspz() {
        return sfspz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.SFSPZ
     *
     * @param sfspz the value for PUB_SPRY.SFSPZ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setSfspz(String sfspz) {
        this.sfspz = sfspz == null ? null : sfspz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.SFDLSPY
     *
     * @return the value of PUB_SPRY.SFDLSPY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getSfdlspy() {
        return sfdlspy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.SFDLSPY
     *
     * @param sfdlspy the value for PUB_SPRY.SFDLSPY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setSfdlspy(String sfdlspy) {
        this.sfdlspy = sfdlspy == null ? null : sfdlspy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.SFRMPSY
     *
     * @return the value of PUB_SPRY.SFRMPSY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getSfrmpsy() {
        return sfrmpsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.SFRMPSY
     *
     * @param sfrmpsy the value for PUB_SPRY.SFRMPSY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setSfrmpsy(String sfrmpsy) {
        this.sfrmpsy = sfrmpsy == null ? null : sfrmpsy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.XM
     *
     * @return the value of PUB_SPRY.XM
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.XM
     *
     * @param xm the value for PUB_SPRY.XM
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.GH
     *
     * @return the value of PUB_SPRY.GH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getGh() {
        return gh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.GH
     *
     * @param gh the value for PUB_SPRY.GH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setGh(String gh) {
        this.gh = gh == null ? null : gh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.BGYY
     *
     * @return the value of PUB_SPRY.BGYY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getBgyy() {
        return bgyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.BGYY
     *
     * @param bgyy the value for PUB_SPRY.BGYY
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setBgyy(String bgyy) {
        this.bgyy = bgyy == null ? null : bgyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.BGSJ
     *
     * @return the value of PUB_SPRY.BGSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Date getBgsj() {
        return bgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.BGSJ
     *
     * @param bgsj the value for PUB_SPRY.BGSJ
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setBgsj(Date bgsj) {
        this.bgsj = bgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.BGFS
     *
     * @return the value of PUB_SPRY.BGFS
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public String getBgfs() {
        return bgfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.BGFS
     *
     * @param bgfs the value for PUB_SPRY.BGFS
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setBgfs(String bgfs) {
        this.bgfs = bgfs == null ? null : bgfs.trim();
    }
}