package software.dzjz.retrieval.model;

public class SpryModelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.AJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Integer ajxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_SPRY.SPRYBH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    private Integer sprybh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.AJXH
     *
     * @return the value of PUB_SPRY.AJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.AJXH
     *
     * @param ajxh the value for PUB_SPRY.AJXH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_SPRY.SPRYBH
     *
     * @return the value of PUB_SPRY.SPRYBH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public Integer getSprybh() {
        return sprybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_SPRY.SPRYBH
     *
     * @param sprybh the value for PUB_SPRY.SPRYBH
     *
     * @mbg.generated Mon Dec 23 16:26:35 CST 2019
     */
    public void setSprybh(Integer sprybh) {
        this.sprybh = sprybh;
    }
}