package software.dzjz.retrieval.model;

import java.util.Date;

public class XtglYhbModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.YHBH
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer yhbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.YHDM
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String yhdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.YHMC
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String yhmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.YHKL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String yhkl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.YHBM
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String yhbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.KLTS
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String klts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.KLDA
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String klda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.YHSF
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String yhsf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.KLSZSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Date klszsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.QJKSSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Date qjkssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.QJJSSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Date qjjssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.QJYY
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String qjyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.GRNZB
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer grnzb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.QTNZB
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer qtnzb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.GRBAJS
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer grbajs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.PHONE
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.XFQX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String xfqx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.SSFWZXQX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String ssfwzxqx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.JBXXJ_CODE
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String jbxxjCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.FAZT
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer fazt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.FASL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer fasl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.FYBH
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer fybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.YHZT
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer yhzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.SLZX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String slzx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.RYPX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer rypx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.PHONENUM
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.DZQMSCSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Date dzqmscsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.USERTEL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String usertel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.YHBMMC
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String yhbmmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.SHANCHU
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String shanchu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.COCALL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String cocall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.SFZ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String sfz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.TEL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.GZZ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String gzz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.ZWURL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String zwurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.SFPTDL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String sfptdl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.SFJAGLY
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private String sfjagly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_YHB.XSSX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    private Integer xssx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.YHBH
     *
     * @return the value of PUB_XTGL_YHB.YHBH
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getYhbh() {
        return yhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.YHBH
     *
     * @param yhbh the value for PUB_XTGL_YHB.YHBH
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setYhbh(Integer yhbh) {
        this.yhbh = yhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.YHDM
     *
     * @return the value of PUB_XTGL_YHB.YHDM
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getYhdm() {
        return yhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.YHDM
     *
     * @param yhdm the value for PUB_XTGL_YHB.YHDM
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setYhdm(String yhdm) {
        this.yhdm = yhdm == null ? null : yhdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.YHMC
     *
     * @return the value of PUB_XTGL_YHB.YHMC
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getYhmc() {
        return yhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.YHMC
     *
     * @param yhmc the value for PUB_XTGL_YHB.YHMC
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setYhmc(String yhmc) {
        this.yhmc = yhmc == null ? null : yhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.YHKL
     *
     * @return the value of PUB_XTGL_YHB.YHKL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getYhkl() {
        return yhkl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.YHKL
     *
     * @param yhkl the value for PUB_XTGL_YHB.YHKL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setYhkl(String yhkl) {
        this.yhkl = yhkl == null ? null : yhkl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.YHBM
     *
     * @return the value of PUB_XTGL_YHB.YHBM
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getYhbm() {
        return yhbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.YHBM
     *
     * @param yhbm the value for PUB_XTGL_YHB.YHBM
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setYhbm(String yhbm) {
        this.yhbm = yhbm == null ? null : yhbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.KLTS
     *
     * @return the value of PUB_XTGL_YHB.KLTS
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getKlts() {
        return klts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.KLTS
     *
     * @param klts the value for PUB_XTGL_YHB.KLTS
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setKlts(String klts) {
        this.klts = klts == null ? null : klts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.KLDA
     *
     * @return the value of PUB_XTGL_YHB.KLDA
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getKlda() {
        return klda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.KLDA
     *
     * @param klda the value for PUB_XTGL_YHB.KLDA
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setKlda(String klda) {
        this.klda = klda == null ? null : klda.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.YHSF
     *
     * @return the value of PUB_XTGL_YHB.YHSF
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getYhsf() {
        return yhsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.YHSF
     *
     * @param yhsf the value for PUB_XTGL_YHB.YHSF
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setYhsf(String yhsf) {
        this.yhsf = yhsf == null ? null : yhsf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.KLSZSJ
     *
     * @return the value of PUB_XTGL_YHB.KLSZSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Date getKlszsj() {
        return klszsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.KLSZSJ
     *
     * @param klszsj the value for PUB_XTGL_YHB.KLSZSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setKlszsj(Date klszsj) {
        this.klszsj = klszsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.QJKSSJ
     *
     * @return the value of PUB_XTGL_YHB.QJKSSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Date getQjkssj() {
        return qjkssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.QJKSSJ
     *
     * @param qjkssj the value for PUB_XTGL_YHB.QJKSSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setQjkssj(Date qjkssj) {
        this.qjkssj = qjkssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.QJJSSJ
     *
     * @return the value of PUB_XTGL_YHB.QJJSSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Date getQjjssj() {
        return qjjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.QJJSSJ
     *
     * @param qjjssj the value for PUB_XTGL_YHB.QJJSSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setQjjssj(Date qjjssj) {
        this.qjjssj = qjjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.QJYY
     *
     * @return the value of PUB_XTGL_YHB.QJYY
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getQjyy() {
        return qjyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.QJYY
     *
     * @param qjyy the value for PUB_XTGL_YHB.QJYY
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setQjyy(String qjyy) {
        this.qjyy = qjyy == null ? null : qjyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.GRNZB
     *
     * @return the value of PUB_XTGL_YHB.GRNZB
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getGrnzb() {
        return grnzb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.GRNZB
     *
     * @param grnzb the value for PUB_XTGL_YHB.GRNZB
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setGrnzb(Integer grnzb) {
        this.grnzb = grnzb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.QTNZB
     *
     * @return the value of PUB_XTGL_YHB.QTNZB
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getQtnzb() {
        return qtnzb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.QTNZB
     *
     * @param qtnzb the value for PUB_XTGL_YHB.QTNZB
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setQtnzb(Integer qtnzb) {
        this.qtnzb = qtnzb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.GRBAJS
     *
     * @return the value of PUB_XTGL_YHB.GRBAJS
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getGrbajs() {
        return grbajs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.GRBAJS
     *
     * @param grbajs the value for PUB_XTGL_YHB.GRBAJS
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setGrbajs(Integer grbajs) {
        this.grbajs = grbajs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.PHONE
     *
     * @return the value of PUB_XTGL_YHB.PHONE
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.PHONE
     *
     * @param phone the value for PUB_XTGL_YHB.PHONE
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.XFQX
     *
     * @return the value of PUB_XTGL_YHB.XFQX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getXfqx() {
        return xfqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.XFQX
     *
     * @param xfqx the value for PUB_XTGL_YHB.XFQX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setXfqx(String xfqx) {
        this.xfqx = xfqx == null ? null : xfqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.SSFWZXQX
     *
     * @return the value of PUB_XTGL_YHB.SSFWZXQX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getSsfwzxqx() {
        return ssfwzxqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.SSFWZXQX
     *
     * @param ssfwzxqx the value for PUB_XTGL_YHB.SSFWZXQX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setSsfwzxqx(String ssfwzxqx) {
        this.ssfwzxqx = ssfwzxqx == null ? null : ssfwzxqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.JBXXJ_CODE
     *
     * @return the value of PUB_XTGL_YHB.JBXXJ_CODE
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getJbxxjCode() {
        return jbxxjCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.JBXXJ_CODE
     *
     * @param jbxxjCode the value for PUB_XTGL_YHB.JBXXJ_CODE
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setJbxxjCode(String jbxxjCode) {
        this.jbxxjCode = jbxxjCode == null ? null : jbxxjCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.FAZT
     *
     * @return the value of PUB_XTGL_YHB.FAZT
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getFazt() {
        return fazt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.FAZT
     *
     * @param fazt the value for PUB_XTGL_YHB.FAZT
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setFazt(Integer fazt) {
        this.fazt = fazt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.FASL
     *
     * @return the value of PUB_XTGL_YHB.FASL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getFasl() {
        return fasl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.FASL
     *
     * @param fasl the value for PUB_XTGL_YHB.FASL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setFasl(Integer fasl) {
        this.fasl = fasl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.FYBH
     *
     * @return the value of PUB_XTGL_YHB.FYBH
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getFybh() {
        return fybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.FYBH
     *
     * @param fybh the value for PUB_XTGL_YHB.FYBH
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setFybh(Integer fybh) {
        this.fybh = fybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.YHZT
     *
     * @return the value of PUB_XTGL_YHB.YHZT
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getYhzt() {
        return yhzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.YHZT
     *
     * @param yhzt the value for PUB_XTGL_YHB.YHZT
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setYhzt(Integer yhzt) {
        this.yhzt = yhzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.SLZX
     *
     * @return the value of PUB_XTGL_YHB.SLZX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getSlzx() {
        return slzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.SLZX
     *
     * @param slzx the value for PUB_XTGL_YHB.SLZX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setSlzx(String slzx) {
        this.slzx = slzx == null ? null : slzx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.RYPX
     *
     * @return the value of PUB_XTGL_YHB.RYPX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getRypx() {
        return rypx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.RYPX
     *
     * @param rypx the value for PUB_XTGL_YHB.RYPX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setRypx(Integer rypx) {
        this.rypx = rypx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.PHONENUM
     *
     * @return the value of PUB_XTGL_YHB.PHONENUM
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.PHONENUM
     *
     * @param phonenum the value for PUB_XTGL_YHB.PHONENUM
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.DZQMSCSJ
     *
     * @return the value of PUB_XTGL_YHB.DZQMSCSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Date getDzqmscsj() {
        return dzqmscsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.DZQMSCSJ
     *
     * @param dzqmscsj the value for PUB_XTGL_YHB.DZQMSCSJ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setDzqmscsj(Date dzqmscsj) {
        this.dzqmscsj = dzqmscsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.USERTEL
     *
     * @return the value of PUB_XTGL_YHB.USERTEL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getUsertel() {
        return usertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.USERTEL
     *
     * @param usertel the value for PUB_XTGL_YHB.USERTEL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setUsertel(String usertel) {
        this.usertel = usertel == null ? null : usertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.YHBMMC
     *
     * @return the value of PUB_XTGL_YHB.YHBMMC
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getYhbmmc() {
        return yhbmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.YHBMMC
     *
     * @param yhbmmc the value for PUB_XTGL_YHB.YHBMMC
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setYhbmmc(String yhbmmc) {
        this.yhbmmc = yhbmmc == null ? null : yhbmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.SHANCHU
     *
     * @return the value of PUB_XTGL_YHB.SHANCHU
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getShanchu() {
        return shanchu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.SHANCHU
     *
     * @param shanchu the value for PUB_XTGL_YHB.SHANCHU
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setShanchu(String shanchu) {
        this.shanchu = shanchu == null ? null : shanchu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.COCALL
     *
     * @return the value of PUB_XTGL_YHB.COCALL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getCocall() {
        return cocall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.COCALL
     *
     * @param cocall the value for PUB_XTGL_YHB.COCALL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setCocall(String cocall) {
        this.cocall = cocall == null ? null : cocall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.SFZ
     *
     * @return the value of PUB_XTGL_YHB.SFZ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getSfz() {
        return sfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.SFZ
     *
     * @param sfz the value for PUB_XTGL_YHB.SFZ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setSfz(String sfz) {
        this.sfz = sfz == null ? null : sfz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.TEL
     *
     * @return the value of PUB_XTGL_YHB.TEL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.TEL
     *
     * @param tel the value for PUB_XTGL_YHB.TEL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.GZZ
     *
     * @return the value of PUB_XTGL_YHB.GZZ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getGzz() {
        return gzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.GZZ
     *
     * @param gzz the value for PUB_XTGL_YHB.GZZ
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setGzz(String gzz) {
        this.gzz = gzz == null ? null : gzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.ZWURL
     *
     * @return the value of PUB_XTGL_YHB.ZWURL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getZwurl() {
        return zwurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.ZWURL
     *
     * @param zwurl the value for PUB_XTGL_YHB.ZWURL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setZwurl(String zwurl) {
        this.zwurl = zwurl == null ? null : zwurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.SFPTDL
     *
     * @return the value of PUB_XTGL_YHB.SFPTDL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getSfptdl() {
        return sfptdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.SFPTDL
     *
     * @param sfptdl the value for PUB_XTGL_YHB.SFPTDL
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setSfptdl(String sfptdl) {
        this.sfptdl = sfptdl == null ? null : sfptdl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.SFJAGLY
     *
     * @return the value of PUB_XTGL_YHB.SFJAGLY
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public String getSfjagly() {
        return sfjagly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.SFJAGLY
     *
     * @param sfjagly the value for PUB_XTGL_YHB.SFJAGLY
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setSfjagly(String sfjagly) {
        this.sfjagly = sfjagly == null ? null : sfjagly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_YHB.XSSX
     *
     * @return the value of PUB_XTGL_YHB.XSSX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public Integer getXssx() {
        return xssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_YHB.XSSX
     *
     * @param xssx the value for PUB_XTGL_YHB.XSSX
     *
     * @mbg.generated Thu Dec 26 09:46:33 CST 2019
     */
    public void setXssx(Integer xssx) {
        this.xssx = xssx;
    }
}